# Malakocut CLI Ignore List
# Flows matching these rules will be hidden in 'top' mode.
# Format: TYPE:VALUE
# Types: ip, port, proto, domain

# Example:
# port:5353
# ip:192.168.4.1
# domain:googlevideo.com
